// <auto-generated />
using System;
using CodeFirst.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CodeFirst.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20230329045100_nuevo1")]
    partial class nuevo1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CodeFirst.Models.Historial", b =>
                {
                    b.Property<int>("IDHistorial")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IDHistorial"));

                    b.Property<string>("H_Categoria")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("H_Estado")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("H_Pregunta")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("H_Respuesta")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("IDPaciente")
                        .HasColumnType("int");

                    b.HasKey("IDHistorial");

                    b.HasIndex("IDPaciente");

                    b.ToTable("Historials");
                });

            modelBuilder.Entity("CodeFirst.Models.Odontograma", b =>
                {
                    b.Property<int>("IDOdontograma")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IDOdontograma"));

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("IDTratamiento")
                        .HasColumnType("int");

                    b.Property<string>("O_Estado")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("O_Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("O_Posicion")
                        .HasColumnType("int");

                    b.HasKey("IDOdontograma");

                    b.HasIndex("IDTratamiento");

                    b.ToTable("Odontogramas");
                });

            modelBuilder.Entity("CodeFirst.Models.Odontologo", b =>
                {
                    b.Property<int>("IDOdontologo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IDOdontologo"));

                    b.Property<string>("OD_Domicilio")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("OD_Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("OD_Password")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("OD_Telefono")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("OD_Turno")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("OD_Usuario")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IDOdontologo");

                    b.ToTable("Odontologos");
                });

            modelBuilder.Entity("CodeFirst.Models.Paciente", b =>
                {
                    b.Property<int>("IDPaciente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IDPaciente"));

                    b.Property<string>("P_DNI")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("P_Domicilio")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("P_FechaNac")
                        .HasColumnType("date");

                    b.Property<string>("P_Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("P_Ocupacion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("P_Telefono")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IDPaciente");

                    b.ToTable("Pacientes");
                });

            modelBuilder.Entity("CodeFirst.Models.Pago_Tratamiento", b =>
                {
                    b.Property<int>("IDPago_Tramiento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IDPago_Tramiento"));

                    b.Property<int>("IDPaciente")
                        .HasColumnType("int");

                    b.Property<int>("IDTratamiento")
                        .HasColumnType("int");

                    b.Property<DateTime>("PT_Fecha")
                        .HasColumnType("date");

                    b.Property<int>("PT_Monto")
                        .HasColumnType("int");

                    b.HasKey("IDPago_Tramiento");

                    b.HasIndex("IDPaciente");

                    b.HasIndex("IDTratamiento");

                    b.ToTable("Pago_Tratamientos");
                });

            modelBuilder.Entity("CodeFirst.Models.Realiza", b =>
                {
                    b.Property<int>("IDPaciente")
                        .HasColumnType("int");

                    b.Property<int>("IDTratamiento")
                        .HasColumnType("int");

                    b.Property<DateTime>("R_Fecha")
                        .HasColumnType("date");

                    b.Property<string>("R_Procedimiento")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IDPaciente", "IDTratamiento");

                    b.HasIndex("IDTratamiento");

                    b.ToTable("Realizas");
                });

            modelBuilder.Entity("CodeFirst.Models.Receta_Medica", b =>
                {
                    b.Property<int>("IDReceta_Medica")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IDReceta_Medica"));

                    b.Property<string>("Dosis")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("IDTratamiento")
                        .HasColumnType("int");

                    b.Property<string>("Medicamento")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Tiempo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IDReceta_Medica");

                    b.HasIndex("IDTratamiento");

                    b.ToTable("Receta_Medicas");
                });

            modelBuilder.Entity("CodeFirst.Models.Tratamiento", b =>
                {
                    b.Property<int>("IDTratamiento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IDTratamiento"));

                    b.Property<int>("Saldo")
                        .HasColumnType("int");

                    b.Property<string>("T_Diagnostico")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("T_Monto")
                        .HasColumnType("int");

                    b.Property<string>("T_Procedimiento")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("T_Tipo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IDTratamiento");

                    b.ToTable("Tratamientos");
                });

            modelBuilder.Entity("CodeFirst.Models.Tutor_Padre", b =>
                {
                    b.Property<int>("ID_Tutor_Padre")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_Tutor_Padre"));

                    b.Property<int>("IDPaciente")
                        .HasColumnType("int");

                    b.Property<string>("TP_Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TP_Ocupacion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TP_Telefono")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ID_Tutor_Padre");

                    b.HasIndex("IDPaciente");

                    b.ToTable("Tutor_Padres");
                });

            modelBuilder.Entity("CodeFirst.Models.Historial", b =>
                {
                    b.HasOne("CodeFirst.Models.Paciente", "Paciente")
                        .WithMany("Historials")
                        .HasForeignKey("IDPaciente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Paciente");
                });

            modelBuilder.Entity("CodeFirst.Models.Odontograma", b =>
                {
                    b.HasOne("CodeFirst.Models.Tratamiento", "Tratamiento")
                        .WithMany("Odontogramas")
                        .HasForeignKey("IDTratamiento")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tratamiento");
                });

            modelBuilder.Entity("CodeFirst.Models.Pago_Tratamiento", b =>
                {
                    b.HasOne("CodeFirst.Models.Paciente", "Paciente")
                        .WithMany("Pago_Tratamientos")
                        .HasForeignKey("IDPaciente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CodeFirst.Models.Tratamiento", "Tratamiento")
                        .WithMany("Pago_Tratamientos")
                        .HasForeignKey("IDTratamiento")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Paciente");

                    b.Navigation("Tratamiento");
                });

            modelBuilder.Entity("CodeFirst.Models.Realiza", b =>
                {
                    b.HasOne("CodeFirst.Models.Paciente", "Paciente")
                        .WithMany("Realizas")
                        .HasForeignKey("IDPaciente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CodeFirst.Models.Tratamiento", "Tratamiento")
                        .WithMany("Realizas")
                        .HasForeignKey("IDTratamiento")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Paciente");

                    b.Navigation("Tratamiento");
                });

            modelBuilder.Entity("CodeFirst.Models.Receta_Medica", b =>
                {
                    b.HasOne("CodeFirst.Models.Tratamiento", "Tratamiento")
                        .WithMany("Receta_Medicas")
                        .HasForeignKey("IDTratamiento")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tratamiento");
                });

            modelBuilder.Entity("CodeFirst.Models.Tutor_Padre", b =>
                {
                    b.HasOne("CodeFirst.Models.Paciente", "Paciente")
                        .WithMany("Tutor_Padres")
                        .HasForeignKey("IDPaciente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Paciente");
                });

            modelBuilder.Entity("CodeFirst.Models.Paciente", b =>
                {
                    b.Navigation("Historials");

                    b.Navigation("Pago_Tratamientos");

                    b.Navigation("Realizas");

                    b.Navigation("Tutor_Padres");
                });

            modelBuilder.Entity("CodeFirst.Models.Tratamiento", b =>
                {
                    b.Navigation("Odontogramas");

                    b.Navigation("Pago_Tratamientos");

                    b.Navigation("Realizas");

                    b.Navigation("Receta_Medicas");
                });
#pragma warning restore 612, 618
        }
    }
}
